FROM mcr.microsoft.com/dotnet/sdk:7.0 AS build-env
WORKDIR /App

COPY . /App

RUN dotnet restore

RUN dotnet publish PMS.Api -c Release -o out

FROM mcr.microsoft.com/dotnet/aspnet:7.0
WORKDIR /App
COPY --from=build-env /App/out .
EXPOSE 80
EXPOSE 443
ENTRYPOINT ["dotnet", "PMS.Api.dll"]